/**
 * Agent 智能上下文构建器
 *
 * 采用三级注入策略 + Token 预算管理：
 * - L0 始终注入（~800 token 预算）：项目名称/类型/进度/一句话大纲
 * - L1 编辑器感知（~600 token 预算）：当前打开的 Tab 信息
 * - L2 按需获取：通过 Tool 调用获取详细数据
 *
 * 系统提示词总上限 ~4700 tokens（设计 §4.3：P1 加 M2 记忆层 800 + M1 300）。
 */

import { useProjectStore } from '../../stores/project-store'
import { useEditorStore } from '../../stores/editor-store'
import { useWorkflowStore } from '../../stores/workflow-store'
import { useAgentStore, type AgentMode } from '../../stores/agent-store'
import { t, getCurrentLocale } from '../../shared/locale'
import { appendOutputLanguage } from '../prompt-templates'
import { ipc } from '../ipc-client'
import { parseMemoryFile } from '../memory/memory-codec'
import { toolRegistry } from './tool-registry'
import { estimateTokens, truncateToTokenBudget } from './token-budget'

/** M2 作品记忆节 Token 预算（book 精要 + 最新分卷 + 最近章节区间 + shared 段，累计不超过此值） */
const M2_BUDGET_TOKENS = 800

/** P3：shared 段保底配额——节选预算内先预留 shared 再按序累计其余段（评审定案） */
const SHARED_FLOOR_TOKENS = 150

/** 系统提示词总上限（设计 §4.3：身份/L0/L1/Tool ~3000 + M2 800 + M1 300 ≈ 4700） */
const TOTAL_BUDGET_TOKENS = 4700

// ===== 上下文构建 =====

/**
 * 构建 Agent 系统提示词（含上下文和 Tool 描述）
 *
 * 所有部分都受 Token 预算约束。
 */
/**
 * 构建 Agent 系统提示词分段：
 * - base：身份 + L0 + L1 + Tool（稳定内容前置，缓存友好段）
 * - memory：M1 会话摘要（自动生成标注节，预算 300 tokens）+ 可扩展 M2 作品记忆（P1）
 * 语言指令由 buildAgentSystemPrompt 统一追加（保持最末尾，#30）
 */
export function buildAgentSystemSegments(mode: AgentMode): { base: string; memory: string } {
  const sections: string[] = []

  // 1. Agent 身份与行为指导 (~400 tokens)
  sections.push(buildIdentityPrompt(mode))

  // 2. L0 — 始终注入的项目上下文 (~800 tokens 预算)
  const l0 = buildL0ProjectContext()
  if (l0) sections.push(l0)

  // 3. L1 — 编辑器感知上下文 (~600 tokens 预算)
  const l1 = buildL1EditorContext()
  if (l1) sections.push(l1)

  // 4. Tool 系统提示词 (~1200 tokens 预算)
  const toolPrompt = toolRegistry.generateToolPrompt()
  if (toolPrompt) {
    const truncated = truncateToTokenBudget(toolPrompt, 1200)
    const isTruncated = truncated.length < toolPrompt.length
    sections.push(isTruncated
      ? `${truncated}\n\n${t('engine.toolTruncatedNotice').replace('{tools}', toolRegistry.listAll().map(tool => tool.name).join(', '))}`
      : truncated)
  }

  const base = sections.join('\n\n---\n\n')

  // ===== M1 会话摘要节（CCR 滚动摘要，自动生成非用户输入；M2 作品记忆 P1 追加于此） =====
  const memoryParts: string[] = []
  const activeConv = useAgentStore.getState().getActiveConversation()
  const summary = activeConv?.rollingSummary
  if (summary) {
    memoryParts.push(`${t('ccr.conversationSummaryHeader')}\n${t('ccr.autoGeneratedNotice')}\n\n${truncateToTokenBudget(summary, 300)}`)
  }
  return { base, memory: memoryParts.join('\n\n---\n\n') }
}

/** 兼容入口（M1 only，同步）：base + memory + 语言指令（语言指令保持最末尾，优先于一切） */
export function buildAgentSystemPrompt(mode: AgentMode): string {
  const segments = buildAgentSystemSegments(mode)
  return assembleFinalPrompt({ base: segments.base, memoryM1: segments.memory, memoryM2: '' })
}

/**
 * 最终拼装（同步/异步共用）：base + M2 + M1 + 语言指令（语言指令保持最末尾）。
 * 段序：base → M2 作品记忆 → M1 会话摘要（M2 比 M1 稳定，前缀缓存友好，设计 §3）；
 * 超限降级顺序 M1 → M2 → L1 → Tool（设计 §4.3，reviewer F1：此前 3800 上限把 M1+M2 整段一起丢）。
 * 导出供单测直接验证降级顺序（合成超限输入）。
 */
export function assembleFinalPrompt(segments: { base: string; memoryM1: string; memoryM2: string }): string {
  const join = (xs: Array<string | undefined>) => xs.filter((x): x is string => Boolean(x)).join('\n\n---\n\n')
  // 索引：0=base，1=M2，2=M1
  const parts: Array<string | undefined> = [segments.base, segments.memoryM2, segments.memoryM1]
  const full = join(parts)

  if (estimateTokens(full) <= TOTAL_BUDGET_TOKENS) {
    return appendOutputLanguage(full, getCurrentLocale())
  }

  console.warn(`[ContextBuilder] 系统提示词过大 (${estimateTokens(full)} tokens)，按 M1 → M2 → L1 → Tool 顺序降级`)
  // 语言指令后缀（#30：必须保持最末尾；各步预算预留其 token 数）
  const langSuffix = appendOutputLanguage('', getCurrentLocale())
  const langTokens = estimateTokens(langSuffix)
  // 1. 先丢 M1 会话摘要段（压缩滚动摘要，非创作必需）
  parts[2] = undefined
  // 2. 仍超限丢 M2 作品记忆段
  if (estimateTokens(join(parts)) > TOTAL_BUDGET_TOKENS) parts[1] = undefined
  // 3. base 拆回节数组（拼接分隔符 '\n\n---\n\n'），按标题定位裁剪 L1
  const baseSections = (parts[0] ?? '').split('\n\n---\n\n')
  const l1Index = baseSections.findIndex(s => s.startsWith(t('engine.contextEditorHeader')))
  if (l1Index >= 0) {
    baseSections[l1Index] = `${t('engine.contextEditorHeader')}\n${t('engine.contextEditorOmitted')}`
  }
  // 4. 仍超限则裁剪 Tool 至剩余预算（剩余 = 上限 − 语言指令 − 其他节 − 截断提示），保证最终 ≤ 上限
  const marker = `\n\n…${t('engine.toolListTruncated')}`
  const markerTokens = estimateTokens(marker)
  const toolIndex = baseSections.findIndex(s => s.startsWith(t('engine.toolSystemTitle')))
  let toolMarked = false
  if (toolIndex >= 0) {
    const othersTokens = estimateTokens(baseSections.filter((_, i) => i !== toolIndex).join('\n\n---\n\n'))
    const memoryTokens = estimateTokens(join(parts.slice(1)))
    const toolBudget = TOTAL_BUDGET_TOKENS - langTokens - othersTokens - memoryTokens - markerTokens
    if (toolBudget > 0 && estimateTokens(baseSections[toolIndex]) > toolBudget) {
      baseSections[toolIndex] = truncateToTokenBudget(baseSections[toolIndex], toolBudget) + marker
      toolMarked = true
    }
  }
  // 5. 兜底硬截断（各节独立预算下理论不可达）：主体按预算截断，语言指令保持最末尾（#30）。
  //    预算预留截断提示 token——tokenizer 分段拼接非可加，硬截断可能切掉尾部提示，补回保持语义不变量
  const main = join([baseSections.join('\n\n---\n\n'), parts[1], parts[2]])
  const mainBudget = TOTAL_BUDGET_TOKENS - langTokens - (toolMarked ? markerTokens : 0)
  if (estimateTokens(main) > mainBudget) {
    const cut = truncateToTokenBudget(main, mainBudget)
    const suffix = (toolMarked && !cut.includes(marker) ? marker : '') + langSuffix
    return cut + suffix
  }
  return appendOutputLanguage(main, getCurrentLocale())
}

/**
 * 异步版：M2 作品记忆节（memory:* 读盘，预算 800，失败降级仅 M1）。
 * 返回 M1/M2 分两段（F1：超限可按段降级）；最终顺序 M2 → M1 由 assembleFinalPrompt 保证（F2）。
 */
export async function buildAgentSystemSegmentsAsync(mode: AgentMode): Promise<{ base: string; memoryM1: string; memoryM2: string }> {
  const { base, memory: m1 } = buildAgentSystemSegments(mode)
  let m2 = ''
  try {
    const list = (await ipc.invoke('memory:list')) as { file: string; kind: 'chapters' | 'volume' | 'book' | 'shared' | 'unknown'; stale: boolean }[]
    const fresh = list.filter(f => !f.stale)
    // M2 节选只取 book/volume/chapters/shared（F9：未知前缀文件 kind=unknown，不参与注入）
    const book = fresh.find(f => f.kind === 'book')
    // ⚠️ 审阅修正：volume-010.md 字典序在 volume-002.md 前——按文件名中的卷号数值排序（最新卷优先）
    const volumes = fresh.filter(f => f.kind === 'volume').sort((a, b) => {
      const n = (f: string) => Number(f.match(/volume-(\d+)\.md/)?.[1] ?? 0)
      return n(b.file) - n(a.file)
    })
    const chapters = fresh.filter(f => f.kind === 'chapters').sort((a, b) => b.file.localeCompare(a.file)) // 最近区间优先（零填充格式字典序=数值序）
    const shared = fresh.find(f => f.kind === 'shared') // P3：跨会话可复用事实段
    // picks 顺序：shared 最先（先按保底配额截断，used 从实际用量起算 → 其余段共用剩余——见下）
    const picks = [shared, book, ...volumes.slice(0, 1), ...chapters.slice(0, 1)].filter(Boolean) as { file: string; kind: string }[]
    const sections: string[] = []
    let used = 0
    for (const p of picks) {
      if (used >= M2_BUDGET_TOKENS) break
      const raw = await ipc.invoke('memory:read', p.file) as string | null
      if (!raw) continue
      const { body } = parseMemoryFile(raw) ?? { body: raw }
      // P3 保底配额：shared 段独立限额 SHARED_FLOOR_TOKENS（先预留再按序累计其余段——
      // 长书 book/volume 占满预算时 shared 不被完全挤出）；其他段共用 800 − shared 实际用量
      const budget = p.kind === 'shared' ? SHARED_FLOOR_TOKENS : M2_BUDGET_TOKENS - used
      // chapters 文件从尾部节选（F5：最新章节优先——truncateToTokenBudget 从头保留会把最新章节丢光）；book/volume/shared 保持头部节选
      const excerpt = p.kind === 'chapters' ? excerptLatestChapters(body, budget) : truncateToTokenBudget(body, budget)
      sections.push(excerpt)
      used += estimateTokens(excerpt)
    }
    if (sections.length > 0) {
      m2 = `${t('memory.injectedHeader')}\n${sections.join('\n\n')}`
    }
  } catch {
    // M2 读盘失败降级：仅 M1
  }
  return { base, memoryM1: m1, memoryM2: m2 }
}

/**
 * 章节记忆尾部节选（F5）：将 body 按「## 第」块切分，从尾部（最新章节）向前累积到预算——
 * 满窗口时注入最近章节而非最早章节；单块超预算时至少保留最新一块，由 truncateToTokenBudget 兜底。
 * 文件头（如 `# 章节记忆 001-015`）始终保留作为区间标注；book/volume 文件不适用本函数。
 */
function excerptLatestChapters(body: string, maxTokens: number): string {
  if (estimateTokens(body) <= maxTokens) return body
  const parts = body.split('\n## 第')
  const header = parts[0]
  const blocks = parts.slice(1).map(b => `## 第${b}`)
  const picked: string[] = []
  let used = 0
  for (let i = blocks.length - 1; i >= 0; i--) {
    const blockTokens = estimateTokens(blocks[i])
    if (picked.length > 0 && used + blockTokens > maxTokens) break
    picked.unshift(blocks[i])
    used += blockTokens
  }
  return truncateToTokenBudget([header, ...picked].join('\n'), maxTokens)
}

/** 异步版最终拼装：base + memory（M1 + M2）+ 语言指令（语言指令保持最末尾） */
export async function buildAgentSystemPromptAsync(mode: AgentMode): Promise<string> {
  return assembleFinalPrompt(await buildAgentSystemSegmentsAsync(mode))
}

// ===== 内部构建方法 =====

/** Agent 身份提示词 */
function buildIdentityPrompt(mode: AgentMode): string {
  const modeDesc = mode === 'max'
    ? t('engine.modeMax')
    : mode === 'deep'
      ? t('engine.modeDeep')
      : mode === 'reflective'
        ? t('engine.modeReflective')
        : mode === 'balanced'
          ? t('engine.modeBalanced')
          : mode === 'swift'
            ? t('engine.modeSwift')
            : t('engine.modeQuick')

  return `${t('engine.identityTitle')}

${t('engine.identityIntro')}

${modeDesc}

${t('engine.identityCapabilitiesHeader')}
${t('engine.identityCapabilityArchitecture')}
${t('engine.identityCapabilityTools')}
${t('engine.identityCapabilityWorkflows')}
${t('engine.identityCapabilityRag')}

${t('engine.identityRulesHeader')}
${t('engine.identityRuleLanguage')}
${t('engine.identityRuleProfessional')}
${t('engine.identityRuleUseTools')}
${t('engine.identityRuleExplainWriteOps')}
${t('engine.identityRuleMultiStep')}`
}

/**
 * L0 — 始终注入的项目上下文
 * Token 预算：~800 tokens
 */
function buildL0ProjectContext(): string | null {
  const project = useProjectStore.getState().currentProject
  if (!project) return null

  // 旧项目数据库可能缺 novelConfig（类型上非可选），运行时兜底避免崩溃
  const cfg = project.novelConfig ?? {}
  const parts: string[] = [
    t('engine.contextProjectHeader'),
    t('engine.contextProjectName').replace('{name}', project.name),
  ]

  if (cfg.genre) {
    parts.push(`${t('engine.contextGenre').replace('{genre}', cfg.genre)}${cfg.subGenre ? ' · ' + cfg.subGenre : ''}`)
  }
  if (cfg.targetAudience) {
    parts.push(t('engine.contextTargetAudience').replace('{audience}', cfg.targetAudience))
  }
  if (cfg.totalChapters) {
    parts.push(t('engine.contextTotalChapters').replace('{n}', String(cfg.totalChapters)))
  }
  if (cfg.wordsPerChapter) {
    parts.push(t('engine.contextWordsPerChapter').replace('{n}', String(cfg.wordsPerChapter)))
  }
  if (cfg.narrativePOV) {
    const povMap: Record<string, string> = {
      'third_limited': t('engine.povThirdLimited'),
      'first_person': t('engine.povFirstPerson'),
      'third_omniscient': t('engine.povThirdOmniscient'),
      'multi_pov': t('engine.povMulti'),
    }
    parts.push(t('engine.contextPov').replace('{pov}', povMap[cfg.narrativePOV] ?? cfg.narrativePOV))
  }
  if (cfg.coreOutline) {
    // Token 感知截断（~80 tokens 预算）
    const { text, truncated } = applyTokenTruncation(cfg.coreOutline, 80)
    parts.push(`${t('engine.contextCoreOutline').replace('{text}', text)}${truncated ? t('engine.truncatedHint') : ''}`)
  }
  if (cfg.writingStyle) {
    // Token 感知截断（~40 tokens 预算）
    const { text, truncated } = applyTokenTruncation(cfg.writingStyle, 40)
    parts.push(`${t('engine.contextWritingStyle').replace('{text}', text)}${truncated ? t('engine.truncatedHint') : ''}`)
  }

  // 检查 L0 总预算
  const full = parts.join('\n')
  if (estimateTokens(full) > 800) {
    // 裁剪大纲和风格部分（⚠️ 低风险修复：追加截断提示——模型曾把截断后的配置当完整内容回答）
    const trimmed = truncateToTokenBudget(full, 800)
    return trimmed + t('engine.truncatedHint')
  }

  return full
}

/**
 * L1 — 编辑器感知上下文
 * Token 预算：~600 tokens
 */
function buildL1EditorContext(): string | null {
  const parts: string[] = []

  // 当前打开的编辑器 Tab
  const editorState = useEditorStore.getState()
  if (editorState.tabs.length > 0) {
    const activeTab = editorState.tabs.find(tab => tab.id === editorState.activeTabId)
    const tabSummaries = editorState.tabs.slice(0, 5).map(tab => {
      const active = tab.id === editorState.activeTabId ? t('engine.contextTabActive') : ''
      const dirty = tab.dirty ? t('engine.contextTabDirty') : ''
      return `  - ${tab.name} (${tab.type})${active}${dirty}`
    }).join('\n')

    let tabSection = `${t('engine.contextEditorHeader')}\n${t('engine.contextEditorOpenFiles')}\n${tabSummaries}`
    if (editorState.tabs.length > 5) {
      tabSection += `\n  …${t('engine.contextTabsMore').replace('{n}', String(editorState.tabs.length))}`
    }
    parts.push(tabSection)

    // 如果当前活跃 Tab 有内容且不太长，注入内容摘要
    if (activeTab?.content && activeTab.content.length > 0) {
      // Token 感知截断（~120 tokens 预算）
      const { text, truncated } = applyTokenTruncation(activeTab.content, 120)
      const fileHeader = `${t('engine.contextActiveFileHeader')}\n${t('engine.contextActiveFileName').replace('{name}', activeTab.name)}`
      if (truncated) {
        parts.push(`${fileHeader}\n\`\`\`\n${text}\n${t('engine.contextActiveFileTruncated')}\n\`\`\``)
      } else {
        parts.push(`${fileHeader}\n\`\`\`\n${text}\n\`\`\``)
      }
    }
  }

  // 当前工作流状态
  const workflowState = useWorkflowStore.getState()
  if (workflowState.hasActiveRun()) {
    const run = workflowState.currentRun
    if (run) {
      parts.push(`${t('engine.contextWorkflowHeader')}\n${t('engine.contextWorkflowRunning').replace('{title}', run.title).replace('{progress}', `${run.currentStepIndex + 1}/${run.steps.length}`)}`)
    }
  }

  if (parts.length === 0) return null

  const full = parts.join('\n\n')
  if (estimateTokens(full) > 600) {
    return truncateToTokenBudget(full, 600)
  }

  return full
}

// ===== Token 截断辅助 =====

/** Token 感知截断的结果 */
interface TruncationResult {
  text: string
  truncated: boolean
  tokensUsed: number
}

/**
 * 在预算内截断文本，返回截断结果。
 * 统一所有上下文构建中的截断逻辑。
 */
function applyTokenTruncation(text: string, maxTokens: number): TruncationResult {
  const tokens = estimateTokens(text)
  if (tokens <= maxTokens) {
    return { text, truncated: false, tokensUsed: tokens }
  }
  const truncated = truncateToTokenBudget(text, maxTokens)
  return {
    text: truncated,
    truncated: truncated.length < text.length,
    tokensUsed: estimateTokens(truncated),
  }
}
